### ISSUE TITLE
Add translated enums

### ISSUE THREAD

**Issue by 2br-2b** [thegamecracks/discord.py-i18n-demo#2]
### Is your feature request related to a problem? Please describe

It would be nice to have examples of how to use parameterized input.

### Describe the solution you'd like

One thing that would be great is an example of an enum as a parameter. If you add an enum as a parameter, you just need to add the translations and discord.py will automatically handle them. If you follow this example [from the docs](https://discordpy.readthedocs.io/en/latest/interactions/api.html#discord.app_commands.choices), you only need to add `apple`, `banana`, and cherry` to the translator:

```python
class Fruits(enum.Enum):
    apple = 1
    banana = 2
    cherry = 3

@app_commands.command()
@app_commands.describe(fruits='fruits to choose from')
async def fruit(interaction: discord.Interaction, fruits: Fruits):
    await interaction.response.send_message(f'Your favourite fruit is {fruits}.')
```

In this example, (I believe) you only need to replace the `name`s with `locale_str`s

```python
@app_commands.command()
@app_commands.describe(fruits='fruits to choose from')
@app_commands.choices(fruits=[
    Choice(name='apple', value=1),
    Choice(name='banana', value=2),
    Choice(name='cherry', value=3),
])
async def fruit(interaction: discord.Interaction, fruits: Choice[int]):
    await interaction.response.send_message(f'Your favourite fruit is {fruits.name}.')
```

### Describe alternatives you've considered

n/a

### Additional context

Thank you so much for making this project! I'm using this now and learning Fluent to add to my current bot. I hope this project helps a lot of people!

**Comment by thegamecracks** [comment]
Sorry for taking a while to respond! I've added a new cog to implement the choice example, using the decorator form to help gettext auto-detect the localizations.
